version: '3.8'

services:
  db:
    image: m.daocloud.io/docker.io/postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-echomind_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: m.daocloud.io/docker.io/redis:7.2.5-alpine3.20
    restart: always
    ports:
      - "6380:6379"

volumes:
  db-data:
